#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mas_data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MAS_TRABAJO")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertMAS_COMPANY(MAS_COMPANY instance);
    partial void UpdateMAS_COMPANY(MAS_COMPANY instance);
    partial void DeleteMAS_COMPANY(MAS_COMPANY instance);
    partial void InsertMAS_PERSON_COMPANY(MAS_PERSON_COMPANY instance);
    partial void UpdateMAS_PERSON_COMPANY(MAS_PERSON_COMPANY instance);
    partial void DeleteMAS_PERSON_COMPANY(MAS_PERSON_COMPANY instance);
    partial void InsertMAS_PERSON_POSTULANT(MAS_PERSON_POSTULANT instance);
    partial void UpdateMAS_PERSON_POSTULANT(MAS_PERSON_POSTULANT instance);
    partial void DeleteMAS_PERSON_POSTULANT(MAS_PERSON_POSTULANT instance);
    partial void InsertMAS_POSITION(MAS_POSITION instance);
    partial void UpdateMAS_POSITION(MAS_POSITION instance);
    partial void DeleteMAS_POSITION(MAS_POSITION instance);
    partial void InsertMAS_TYPE_IDENTIFICATION(MAS_TYPE_IDENTIFICATION instance);
    partial void UpdateMAS_TYPE_IDENTIFICATION(MAS_TYPE_IDENTIFICATION instance);
    partial void DeleteMAS_TYPE_IDENTIFICATION(MAS_TYPE_IDENTIFICATION instance);
    partial void InsertMAS_TYPE_INDUSTRY(MAS_TYPE_INDUSTRY instance);
    partial void UpdateMAS_TYPE_INDUSTRY(MAS_TYPE_INDUSTRY instance);
    partial void DeleteMAS_TYPE_INDUSTRY(MAS_TYPE_INDUSTRY instance);
    partial void InsertMAS_USER_COMPANY(MAS_USER_COMPANY instance);
    partial void UpdateMAS_USER_COMPANY(MAS_USER_COMPANY instance);
    partial void DeleteMAS_USER_COMPANY(MAS_USER_COMPANY instance);
    partial void InsertMAS_USER_POSTULANT(MAS_USER_POSTULANT instance);
    partial void UpdateMAS_USER_POSTULANT(MAS_USER_POSTULANT instance);
    partial void DeleteMAS_USER_POSTULANT(MAS_USER_POSTULANT instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::mas_data.Properties.Settings.Default.MAS_TRABAJOConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MAS_COMPANY> MAS_COMPANY
		{
			get
			{
				return this.GetTable<MAS_COMPANY>();
			}
		}
		
		public System.Data.Linq.Table<MAS_PERSON_COMPANY> MAS_PERSON_COMPANY
		{
			get
			{
				return this.GetTable<MAS_PERSON_COMPANY>();
			}
		}
		
		public System.Data.Linq.Table<MAS_PERSON_POSTULANT> MAS_PERSON_POSTULANT
		{
			get
			{
				return this.GetTable<MAS_PERSON_POSTULANT>();
			}
		}
		
		public System.Data.Linq.Table<MAS_POSITION> MAS_POSITION
		{
			get
			{
				return this.GetTable<MAS_POSITION>();
			}
		}
		
		public System.Data.Linq.Table<MAS_TYPE_IDENTIFICATION> MAS_TYPE_IDENTIFICATION
		{
			get
			{
				return this.GetTable<MAS_TYPE_IDENTIFICATION>();
			}
		}
		
		public System.Data.Linq.Table<MAS_TYPE_INDUSTRY> MAS_TYPE_INDUSTRY
		{
			get
			{
				return this.GetTable<MAS_TYPE_INDUSTRY>();
			}
		}
		
		public System.Data.Linq.Table<MAS_USER_COMPANY> MAS_USER_COMPANY
		{
			get
			{
				return this.GetTable<MAS_USER_COMPANY>();
			}
		}
		
		public System.Data.Linq.Table<MAS_USER_POSTULANT> MAS_USER_POSTULANT
		{
			get
			{
				return this.GetTable<MAS_USER_POSTULANT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_COMPANY")]
	public partial class MAS_COMPANY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _COM_ID;
		
		private string _COM_COMPANY_NAME;
		
		private string _COM_BUSINESS_NAME;
		
		private string _COM_ADDRESS;
		
		private string _COM_PHONE;
		
		private System.Nullable<int> _COM_FK_TYPE_INDUSTRY;
		
		private System.Nullable<int> _COM_QUANTITY_EMPLOYEES;
		
		private System.Nullable<int> _COM_FK_PERSON_COMPANY;
		
		private bool _COM_STATE;
		
		private EntityRef<MAS_PERSON_COMPANY> _MAS_PERSON_COMPANY;
		
		private EntityRef<MAS_TYPE_INDUSTRY> _MAS_TYPE_INDUSTRY;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCOM_IDChanging(int value);
    partial void OnCOM_IDChanged();
    partial void OnCOM_COMPANY_NAMEChanging(string value);
    partial void OnCOM_COMPANY_NAMEChanged();
    partial void OnCOM_BUSINESS_NAMEChanging(string value);
    partial void OnCOM_BUSINESS_NAMEChanged();
    partial void OnCOM_ADDRESSChanging(string value);
    partial void OnCOM_ADDRESSChanged();
    partial void OnCOM_PHONEChanging(string value);
    partial void OnCOM_PHONEChanged();
    partial void OnCOM_FK_TYPE_INDUSTRYChanging(System.Nullable<int> value);
    partial void OnCOM_FK_TYPE_INDUSTRYChanged();
    partial void OnCOM_QUANTITY_EMPLOYEESChanging(System.Nullable<int> value);
    partial void OnCOM_QUANTITY_EMPLOYEESChanged();
    partial void OnCOM_FK_PERSON_COMPANYChanging(System.Nullable<int> value);
    partial void OnCOM_FK_PERSON_COMPANYChanged();
    partial void OnCOM_STATEChanging(bool value);
    partial void OnCOM_STATEChanged();
    #endregion
		
		public MAS_COMPANY()
		{
			this._MAS_PERSON_COMPANY = default(EntityRef<MAS_PERSON_COMPANY>);
			this._MAS_TYPE_INDUSTRY = default(EntityRef<MAS_TYPE_INDUSTRY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int COM_ID
		{
			get
			{
				return this._COM_ID;
			}
			set
			{
				if ((this._COM_ID != value))
				{
					this.OnCOM_IDChanging(value);
					this.SendPropertyChanging();
					this._COM_ID = value;
					this.SendPropertyChanged("COM_ID");
					this.OnCOM_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_COMPANY_NAME", DbType="NVarChar(100)")]
		public string COM_COMPANY_NAME
		{
			get
			{
				return this._COM_COMPANY_NAME;
			}
			set
			{
				if ((this._COM_COMPANY_NAME != value))
				{
					this.OnCOM_COMPANY_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COM_COMPANY_NAME = value;
					this.SendPropertyChanged("COM_COMPANY_NAME");
					this.OnCOM_COMPANY_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_BUSINESS_NAME", DbType="NVarChar(100)")]
		public string COM_BUSINESS_NAME
		{
			get
			{
				return this._COM_BUSINESS_NAME;
			}
			set
			{
				if ((this._COM_BUSINESS_NAME != value))
				{
					this.OnCOM_BUSINESS_NAMEChanging(value);
					this.SendPropertyChanging();
					this._COM_BUSINESS_NAME = value;
					this.SendPropertyChanged("COM_BUSINESS_NAME");
					this.OnCOM_BUSINESS_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_ADDRESS", DbType="NVarChar(250)")]
		public string COM_ADDRESS
		{
			get
			{
				return this._COM_ADDRESS;
			}
			set
			{
				if ((this._COM_ADDRESS != value))
				{
					this.OnCOM_ADDRESSChanging(value);
					this.SendPropertyChanging();
					this._COM_ADDRESS = value;
					this.SendPropertyChanged("COM_ADDRESS");
					this.OnCOM_ADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_PHONE", DbType="NVarChar(20)")]
		public string COM_PHONE
		{
			get
			{
				return this._COM_PHONE;
			}
			set
			{
				if ((this._COM_PHONE != value))
				{
					this.OnCOM_PHONEChanging(value);
					this.SendPropertyChanging();
					this._COM_PHONE = value;
					this.SendPropertyChanged("COM_PHONE");
					this.OnCOM_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_FK_TYPE_INDUSTRY", DbType="Int")]
		public System.Nullable<int> COM_FK_TYPE_INDUSTRY
		{
			get
			{
				return this._COM_FK_TYPE_INDUSTRY;
			}
			set
			{
				if ((this._COM_FK_TYPE_INDUSTRY != value))
				{
					if (this._MAS_TYPE_INDUSTRY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOM_FK_TYPE_INDUSTRYChanging(value);
					this.SendPropertyChanging();
					this._COM_FK_TYPE_INDUSTRY = value;
					this.SendPropertyChanged("COM_FK_TYPE_INDUSTRY");
					this.OnCOM_FK_TYPE_INDUSTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_QUANTITY_EMPLOYEES", DbType="Int")]
		public System.Nullable<int> COM_QUANTITY_EMPLOYEES
		{
			get
			{
				return this._COM_QUANTITY_EMPLOYEES;
			}
			set
			{
				if ((this._COM_QUANTITY_EMPLOYEES != value))
				{
					this.OnCOM_QUANTITY_EMPLOYEESChanging(value);
					this.SendPropertyChanging();
					this._COM_QUANTITY_EMPLOYEES = value;
					this.SendPropertyChanged("COM_QUANTITY_EMPLOYEES");
					this.OnCOM_QUANTITY_EMPLOYEESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_FK_PERSON_COMPANY", DbType="Int")]
		public System.Nullable<int> COM_FK_PERSON_COMPANY
		{
			get
			{
				return this._COM_FK_PERSON_COMPANY;
			}
			set
			{
				if ((this._COM_FK_PERSON_COMPANY != value))
				{
					if (this._MAS_PERSON_COMPANY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCOM_FK_PERSON_COMPANYChanging(value);
					this.SendPropertyChanging();
					this._COM_FK_PERSON_COMPANY = value;
					this.SendPropertyChanged("COM_FK_PERSON_COMPANY");
					this.OnCOM_FK_PERSON_COMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COM_STATE", DbType="Bit NOT NULL")]
		public bool COM_STATE
		{
			get
			{
				return this._COM_STATE;
			}
			set
			{
				if ((this._COM_STATE != value))
				{
					this.OnCOM_STATEChanging(value);
					this.SendPropertyChanging();
					this._COM_STATE = value;
					this.SendPropertyChanged("COM_STATE");
					this.OnCOM_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_PERSON_COMPANY_MAS_COMPANY", Storage="_MAS_PERSON_COMPANY", ThisKey="COM_FK_PERSON_COMPANY", OtherKey="PER_ID", IsForeignKey=true)]
		public MAS_PERSON_COMPANY MAS_PERSON_COMPANY
		{
			get
			{
				return this._MAS_PERSON_COMPANY.Entity;
			}
			set
			{
				MAS_PERSON_COMPANY previousValue = this._MAS_PERSON_COMPANY.Entity;
				if (((previousValue != value) 
							|| (this._MAS_PERSON_COMPANY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAS_PERSON_COMPANY.Entity = null;
						previousValue.MAS_COMPANY.Remove(this);
					}
					this._MAS_PERSON_COMPANY.Entity = value;
					if ((value != null))
					{
						value.MAS_COMPANY.Add(this);
						this._COM_FK_PERSON_COMPANY = value.PER_ID;
					}
					else
					{
						this._COM_FK_PERSON_COMPANY = default(Nullable<int>);
					}
					this.SendPropertyChanged("MAS_PERSON_COMPANY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_TYPE_INDUSTRY_MAS_COMPANY", Storage="_MAS_TYPE_INDUSTRY", ThisKey="COM_FK_TYPE_INDUSTRY", OtherKey="TYP_ID", IsForeignKey=true)]
		public MAS_TYPE_INDUSTRY MAS_TYPE_INDUSTRY
		{
			get
			{
				return this._MAS_TYPE_INDUSTRY.Entity;
			}
			set
			{
				MAS_TYPE_INDUSTRY previousValue = this._MAS_TYPE_INDUSTRY.Entity;
				if (((previousValue != value) 
							|| (this._MAS_TYPE_INDUSTRY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAS_TYPE_INDUSTRY.Entity = null;
						previousValue.MAS_COMPANY.Remove(this);
					}
					this._MAS_TYPE_INDUSTRY.Entity = value;
					if ((value != null))
					{
						value.MAS_COMPANY.Add(this);
						this._COM_FK_TYPE_INDUSTRY = value.TYP_ID;
					}
					else
					{
						this._COM_FK_TYPE_INDUSTRY = default(Nullable<int>);
					}
					this.SendPropertyChanged("MAS_TYPE_INDUSTRY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_PERSON_COMPANY")]
	public partial class MAS_PERSON_COMPANY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PER_ID;
		
		private string _PER_FIRST_NAME;
		
		private string _PER_SECOND_NAME;
		
		private string _PER_LAST_NAME;
		
		private string _PER_SUR_NAME;
		
		private int _PER_FK_TYPE_IDENTIFICATION;
		
		private string _PER_NUMBER_IDENTIFICATION;
		
		private int _PER_FK_POSITION;
		
		private bool _PER_STATE;
		
		private EntitySet<MAS_COMPANY> _MAS_COMPANY;
		
		private EntitySet<MAS_USER_COMPANY> _MAS_USER_COMPANY;
		
		private EntityRef<MAS_POSITION> _MAS_POSITION;
		
		private EntityRef<MAS_TYPE_IDENTIFICATION> _MAS_TYPE_IDENTIFICATION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPER_IDChanging(int value);
    partial void OnPER_IDChanged();
    partial void OnPER_FIRST_NAMEChanging(string value);
    partial void OnPER_FIRST_NAMEChanged();
    partial void OnPER_SECOND_NAMEChanging(string value);
    partial void OnPER_SECOND_NAMEChanged();
    partial void OnPER_LAST_NAMEChanging(string value);
    partial void OnPER_LAST_NAMEChanged();
    partial void OnPER_SUR_NAMEChanging(string value);
    partial void OnPER_SUR_NAMEChanged();
    partial void OnPER_FK_TYPE_IDENTIFICATIONChanging(int value);
    partial void OnPER_FK_TYPE_IDENTIFICATIONChanged();
    partial void OnPER_NUMBER_IDENTIFICATIONChanging(string value);
    partial void OnPER_NUMBER_IDENTIFICATIONChanged();
    partial void OnPER_FK_POSITIONChanging(int value);
    partial void OnPER_FK_POSITIONChanged();
    partial void OnPER_STATEChanging(bool value);
    partial void OnPER_STATEChanged();
    #endregion
		
		public MAS_PERSON_COMPANY()
		{
			this._MAS_COMPANY = new EntitySet<MAS_COMPANY>(new Action<MAS_COMPANY>(this.attach_MAS_COMPANY), new Action<MAS_COMPANY>(this.detach_MAS_COMPANY));
			this._MAS_USER_COMPANY = new EntitySet<MAS_USER_COMPANY>(new Action<MAS_USER_COMPANY>(this.attach_MAS_USER_COMPANY), new Action<MAS_USER_COMPANY>(this.detach_MAS_USER_COMPANY));
			this._MAS_POSITION = default(EntityRef<MAS_POSITION>);
			this._MAS_TYPE_IDENTIFICATION = default(EntityRef<MAS_TYPE_IDENTIFICATION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int PER_ID
		{
			get
			{
				return this._PER_ID;
			}
			set
			{
				if ((this._PER_ID != value))
				{
					this.OnPER_IDChanging(value);
					this.SendPropertyChanging();
					this._PER_ID = value;
					this.SendPropertyChanged("PER_ID");
					this.OnPER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_FIRST_NAME", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string PER_FIRST_NAME
		{
			get
			{
				return this._PER_FIRST_NAME;
			}
			set
			{
				if ((this._PER_FIRST_NAME != value))
				{
					this.OnPER_FIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_FIRST_NAME = value;
					this.SendPropertyChanged("PER_FIRST_NAME");
					this.OnPER_FIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_SECOND_NAME", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string PER_SECOND_NAME
		{
			get
			{
				return this._PER_SECOND_NAME;
			}
			set
			{
				if ((this._PER_SECOND_NAME != value))
				{
					this.OnPER_SECOND_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_SECOND_NAME = value;
					this.SendPropertyChanged("PER_SECOND_NAME");
					this.OnPER_SECOND_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_LAST_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PER_LAST_NAME
		{
			get
			{
				return this._PER_LAST_NAME;
			}
			set
			{
				if ((this._PER_LAST_NAME != value))
				{
					this.OnPER_LAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_LAST_NAME = value;
					this.SendPropertyChanged("PER_LAST_NAME");
					this.OnPER_LAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_SUR_NAME", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PER_SUR_NAME
		{
			get
			{
				return this._PER_SUR_NAME;
			}
			set
			{
				if ((this._PER_SUR_NAME != value))
				{
					this.OnPER_SUR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_SUR_NAME = value;
					this.SendPropertyChanged("PER_SUR_NAME");
					this.OnPER_SUR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_FK_TYPE_IDENTIFICATION", DbType="Int NOT NULL")]
		public int PER_FK_TYPE_IDENTIFICATION
		{
			get
			{
				return this._PER_FK_TYPE_IDENTIFICATION;
			}
			set
			{
				if ((this._PER_FK_TYPE_IDENTIFICATION != value))
				{
					if (this._MAS_TYPE_IDENTIFICATION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPER_FK_TYPE_IDENTIFICATIONChanging(value);
					this.SendPropertyChanging();
					this._PER_FK_TYPE_IDENTIFICATION = value;
					this.SendPropertyChanged("PER_FK_TYPE_IDENTIFICATION");
					this.OnPER_FK_TYPE_IDENTIFICATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_NUMBER_IDENTIFICATION", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string PER_NUMBER_IDENTIFICATION
		{
			get
			{
				return this._PER_NUMBER_IDENTIFICATION;
			}
			set
			{
				if ((this._PER_NUMBER_IDENTIFICATION != value))
				{
					this.OnPER_NUMBER_IDENTIFICATIONChanging(value);
					this.SendPropertyChanging();
					this._PER_NUMBER_IDENTIFICATION = value;
					this.SendPropertyChanged("PER_NUMBER_IDENTIFICATION");
					this.OnPER_NUMBER_IDENTIFICATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_FK_POSITION", DbType="Int NOT NULL")]
		public int PER_FK_POSITION
		{
			get
			{
				return this._PER_FK_POSITION;
			}
			set
			{
				if ((this._PER_FK_POSITION != value))
				{
					if (this._MAS_POSITION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPER_FK_POSITIONChanging(value);
					this.SendPropertyChanging();
					this._PER_FK_POSITION = value;
					this.SendPropertyChanged("PER_FK_POSITION");
					this.OnPER_FK_POSITIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_STATE", DbType="Bit NOT NULL")]
		public bool PER_STATE
		{
			get
			{
				return this._PER_STATE;
			}
			set
			{
				if ((this._PER_STATE != value))
				{
					this.OnPER_STATEChanging(value);
					this.SendPropertyChanging();
					this._PER_STATE = value;
					this.SendPropertyChanged("PER_STATE");
					this.OnPER_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_PERSON_COMPANY_MAS_COMPANY", Storage="_MAS_COMPANY", ThisKey="PER_ID", OtherKey="COM_FK_PERSON_COMPANY")]
		public EntitySet<MAS_COMPANY> MAS_COMPANY
		{
			get
			{
				return this._MAS_COMPANY;
			}
			set
			{
				this._MAS_COMPANY.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_PERSON_COMPANY_MAS_USER_COMPANY", Storage="_MAS_USER_COMPANY", ThisKey="PER_ID", OtherKey="USE_FK_PERSON_COMPANY")]
		public EntitySet<MAS_USER_COMPANY> MAS_USER_COMPANY
		{
			get
			{
				return this._MAS_USER_COMPANY;
			}
			set
			{
				this._MAS_USER_COMPANY.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_POSITION_MAS_PERSON_COMPANY", Storage="_MAS_POSITION", ThisKey="PER_FK_POSITION", OtherKey="POS_ID", IsForeignKey=true)]
		public MAS_POSITION MAS_POSITION
		{
			get
			{
				return this._MAS_POSITION.Entity;
			}
			set
			{
				MAS_POSITION previousValue = this._MAS_POSITION.Entity;
				if (((previousValue != value) 
							|| (this._MAS_POSITION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAS_POSITION.Entity = null;
						previousValue.MAS_PERSON_COMPANY.Remove(this);
					}
					this._MAS_POSITION.Entity = value;
					if ((value != null))
					{
						value.MAS_PERSON_COMPANY.Add(this);
						this._PER_FK_POSITION = value.POS_ID;
					}
					else
					{
						this._PER_FK_POSITION = default(int);
					}
					this.SendPropertyChanged("MAS_POSITION");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_TYPE_IDENTIFICATION_MAS_PERSON_COMPANY", Storage="_MAS_TYPE_IDENTIFICATION", ThisKey="PER_FK_TYPE_IDENTIFICATION", OtherKey="TYP_ID", IsForeignKey=true)]
		public MAS_TYPE_IDENTIFICATION MAS_TYPE_IDENTIFICATION
		{
			get
			{
				return this._MAS_TYPE_IDENTIFICATION.Entity;
			}
			set
			{
				MAS_TYPE_IDENTIFICATION previousValue = this._MAS_TYPE_IDENTIFICATION.Entity;
				if (((previousValue != value) 
							|| (this._MAS_TYPE_IDENTIFICATION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAS_TYPE_IDENTIFICATION.Entity = null;
						previousValue.MAS_PERSON_COMPANY.Remove(this);
					}
					this._MAS_TYPE_IDENTIFICATION.Entity = value;
					if ((value != null))
					{
						value.MAS_PERSON_COMPANY.Add(this);
						this._PER_FK_TYPE_IDENTIFICATION = value.TYP_ID;
					}
					else
					{
						this._PER_FK_TYPE_IDENTIFICATION = default(int);
					}
					this.SendPropertyChanged("MAS_TYPE_IDENTIFICATION");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MAS_COMPANY(MAS_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_PERSON_COMPANY = this;
		}
		
		private void detach_MAS_COMPANY(MAS_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_PERSON_COMPANY = null;
		}
		
		private void attach_MAS_USER_COMPANY(MAS_USER_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_PERSON_COMPANY = this;
		}
		
		private void detach_MAS_USER_COMPANY(MAS_USER_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_PERSON_COMPANY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_PERSON_POSTULANT")]
	public partial class MAS_PERSON_POSTULANT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PER_ID;
		
		private string _PER_FIRST_NAME;
		
		private string _PER_SECOND_NAME;
		
		private string _PER_LAST_NAME;
		
		private string _PER_SUR_NAME;
		
		private System.Nullable<int> _PER_FK_TYPE_IDENTIFICATION;
		
		private string _PER_NUMBER_IDENTIFICATION;
		
		private System.Nullable<bool> _PER_STATE;
		
		private EntitySet<MAS_USER_POSTULANT> _MAS_USER_POSTULANT;
		
		private EntityRef<MAS_TYPE_IDENTIFICATION> _MAS_TYPE_IDENTIFICATION;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPER_IDChanging(int value);
    partial void OnPER_IDChanged();
    partial void OnPER_FIRST_NAMEChanging(string value);
    partial void OnPER_FIRST_NAMEChanged();
    partial void OnPER_SECOND_NAMEChanging(string value);
    partial void OnPER_SECOND_NAMEChanged();
    partial void OnPER_LAST_NAMEChanging(string value);
    partial void OnPER_LAST_NAMEChanged();
    partial void OnPER_SUR_NAMEChanging(string value);
    partial void OnPER_SUR_NAMEChanged();
    partial void OnPER_FK_TYPE_IDENTIFICATIONChanging(System.Nullable<int> value);
    partial void OnPER_FK_TYPE_IDENTIFICATIONChanged();
    partial void OnPER_NUMBER_IDENTIFICATIONChanging(string value);
    partial void OnPER_NUMBER_IDENTIFICATIONChanged();
    partial void OnPER_STATEChanging(System.Nullable<bool> value);
    partial void OnPER_STATEChanged();
    #endregion
		
		public MAS_PERSON_POSTULANT()
		{
			this._MAS_USER_POSTULANT = new EntitySet<MAS_USER_POSTULANT>(new Action<MAS_USER_POSTULANT>(this.attach_MAS_USER_POSTULANT), new Action<MAS_USER_POSTULANT>(this.detach_MAS_USER_POSTULANT));
			this._MAS_TYPE_IDENTIFICATION = default(EntityRef<MAS_TYPE_IDENTIFICATION>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PER_ID
		{
			get
			{
				return this._PER_ID;
			}
			set
			{
				if ((this._PER_ID != value))
				{
					this.OnPER_IDChanging(value);
					this.SendPropertyChanging();
					this._PER_ID = value;
					this.SendPropertyChanged("PER_ID");
					this.OnPER_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_FIRST_NAME", DbType="NVarChar(40)")]
		public string PER_FIRST_NAME
		{
			get
			{
				return this._PER_FIRST_NAME;
			}
			set
			{
				if ((this._PER_FIRST_NAME != value))
				{
					this.OnPER_FIRST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_FIRST_NAME = value;
					this.SendPropertyChanged("PER_FIRST_NAME");
					this.OnPER_FIRST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_SECOND_NAME", DbType="NVarChar(40)")]
		public string PER_SECOND_NAME
		{
			get
			{
				return this._PER_SECOND_NAME;
			}
			set
			{
				if ((this._PER_SECOND_NAME != value))
				{
					this.OnPER_SECOND_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_SECOND_NAME = value;
					this.SendPropertyChanged("PER_SECOND_NAME");
					this.OnPER_SECOND_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_LAST_NAME", DbType="NVarChar(40)")]
		public string PER_LAST_NAME
		{
			get
			{
				return this._PER_LAST_NAME;
			}
			set
			{
				if ((this._PER_LAST_NAME != value))
				{
					this.OnPER_LAST_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_LAST_NAME = value;
					this.SendPropertyChanged("PER_LAST_NAME");
					this.OnPER_LAST_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_SUR_NAME", DbType="NVarChar(50)")]
		public string PER_SUR_NAME
		{
			get
			{
				return this._PER_SUR_NAME;
			}
			set
			{
				if ((this._PER_SUR_NAME != value))
				{
					this.OnPER_SUR_NAMEChanging(value);
					this.SendPropertyChanging();
					this._PER_SUR_NAME = value;
					this.SendPropertyChanged("PER_SUR_NAME");
					this.OnPER_SUR_NAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_FK_TYPE_IDENTIFICATION", DbType="Int")]
		public System.Nullable<int> PER_FK_TYPE_IDENTIFICATION
		{
			get
			{
				return this._PER_FK_TYPE_IDENTIFICATION;
			}
			set
			{
				if ((this._PER_FK_TYPE_IDENTIFICATION != value))
				{
					if (this._MAS_TYPE_IDENTIFICATION.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPER_FK_TYPE_IDENTIFICATIONChanging(value);
					this.SendPropertyChanging();
					this._PER_FK_TYPE_IDENTIFICATION = value;
					this.SendPropertyChanged("PER_FK_TYPE_IDENTIFICATION");
					this.OnPER_FK_TYPE_IDENTIFICATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_NUMBER_IDENTIFICATION", DbType="NVarChar(30)")]
		public string PER_NUMBER_IDENTIFICATION
		{
			get
			{
				return this._PER_NUMBER_IDENTIFICATION;
			}
			set
			{
				if ((this._PER_NUMBER_IDENTIFICATION != value))
				{
					this.OnPER_NUMBER_IDENTIFICATIONChanging(value);
					this.SendPropertyChanging();
					this._PER_NUMBER_IDENTIFICATION = value;
					this.SendPropertyChanged("PER_NUMBER_IDENTIFICATION");
					this.OnPER_NUMBER_IDENTIFICATIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PER_STATE", DbType="Bit")]
		public System.Nullable<bool> PER_STATE
		{
			get
			{
				return this._PER_STATE;
			}
			set
			{
				if ((this._PER_STATE != value))
				{
					this.OnPER_STATEChanging(value);
					this.SendPropertyChanging();
					this._PER_STATE = value;
					this.SendPropertyChanged("PER_STATE");
					this.OnPER_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_PERSON_POSTULANT_MAS_USER_POSTULANT", Storage="_MAS_USER_POSTULANT", ThisKey="PER_ID", OtherKey="USE_FK_PERSON_POSTULANT")]
		public EntitySet<MAS_USER_POSTULANT> MAS_USER_POSTULANT
		{
			get
			{
				return this._MAS_USER_POSTULANT;
			}
			set
			{
				this._MAS_USER_POSTULANT.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_TYPE_IDENTIFICATION_MAS_PERSON_POSTULANT", Storage="_MAS_TYPE_IDENTIFICATION", ThisKey="PER_FK_TYPE_IDENTIFICATION", OtherKey="TYP_ID", IsForeignKey=true)]
		public MAS_TYPE_IDENTIFICATION MAS_TYPE_IDENTIFICATION
		{
			get
			{
				return this._MAS_TYPE_IDENTIFICATION.Entity;
			}
			set
			{
				MAS_TYPE_IDENTIFICATION previousValue = this._MAS_TYPE_IDENTIFICATION.Entity;
				if (((previousValue != value) 
							|| (this._MAS_TYPE_IDENTIFICATION.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAS_TYPE_IDENTIFICATION.Entity = null;
						previousValue.MAS_PERSON_POSTULANT.Remove(this);
					}
					this._MAS_TYPE_IDENTIFICATION.Entity = value;
					if ((value != null))
					{
						value.MAS_PERSON_POSTULANT.Add(this);
						this._PER_FK_TYPE_IDENTIFICATION = value.TYP_ID;
					}
					else
					{
						this._PER_FK_TYPE_IDENTIFICATION = default(Nullable<int>);
					}
					this.SendPropertyChanged("MAS_TYPE_IDENTIFICATION");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MAS_USER_POSTULANT(MAS_USER_POSTULANT entity)
		{
			this.SendPropertyChanging();
			entity.MAS_PERSON_POSTULANT = this;
		}
		
		private void detach_MAS_USER_POSTULANT(MAS_USER_POSTULANT entity)
		{
			this.SendPropertyChanging();
			entity.MAS_PERSON_POSTULANT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_POSITION")]
	public partial class MAS_POSITION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _POS_ID;
		
		private string _POS_DESCRIPTION;
		
		private System.Nullable<bool> _POS_STATE;
		
		private EntitySet<MAS_PERSON_COMPANY> _MAS_PERSON_COMPANY;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPOS_IDChanging(int value);
    partial void OnPOS_IDChanged();
    partial void OnPOS_DESCRIPTIONChanging(string value);
    partial void OnPOS_DESCRIPTIONChanged();
    partial void OnPOS_STATEChanging(System.Nullable<bool> value);
    partial void OnPOS_STATEChanged();
    #endregion
		
		public MAS_POSITION()
		{
			this._MAS_PERSON_COMPANY = new EntitySet<MAS_PERSON_COMPANY>(new Action<MAS_PERSON_COMPANY>(this.attach_MAS_PERSON_COMPANY), new Action<MAS_PERSON_COMPANY>(this.detach_MAS_PERSON_COMPANY));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int POS_ID
		{
			get
			{
				return this._POS_ID;
			}
			set
			{
				if ((this._POS_ID != value))
				{
					this.OnPOS_IDChanging(value);
					this.SendPropertyChanging();
					this._POS_ID = value;
					this.SendPropertyChanged("POS_ID");
					this.OnPOS_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_DESCRIPTION", DbType="NVarChar(200)")]
		public string POS_DESCRIPTION
		{
			get
			{
				return this._POS_DESCRIPTION;
			}
			set
			{
				if ((this._POS_DESCRIPTION != value))
				{
					this.OnPOS_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._POS_DESCRIPTION = value;
					this.SendPropertyChanged("POS_DESCRIPTION");
					this.OnPOS_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POS_STATE", DbType="Bit")]
		public System.Nullable<bool> POS_STATE
		{
			get
			{
				return this._POS_STATE;
			}
			set
			{
				if ((this._POS_STATE != value))
				{
					this.OnPOS_STATEChanging(value);
					this.SendPropertyChanging();
					this._POS_STATE = value;
					this.SendPropertyChanged("POS_STATE");
					this.OnPOS_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_POSITION_MAS_PERSON_COMPANY", Storage="_MAS_PERSON_COMPANY", ThisKey="POS_ID", OtherKey="PER_FK_POSITION")]
		public EntitySet<MAS_PERSON_COMPANY> MAS_PERSON_COMPANY
		{
			get
			{
				return this._MAS_PERSON_COMPANY;
			}
			set
			{
				this._MAS_PERSON_COMPANY.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MAS_PERSON_COMPANY(MAS_PERSON_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_POSITION = this;
		}
		
		private void detach_MAS_PERSON_COMPANY(MAS_PERSON_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_POSITION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_TYPE_IDENTIFICATION")]
	public partial class MAS_TYPE_IDENTIFICATION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TYP_ID;
		
		private string _TYP_DESCRIPTION;
		
		private System.Nullable<bool> _TYP_STATE;
		
		private EntitySet<MAS_PERSON_COMPANY> _MAS_PERSON_COMPANY;
		
		private EntitySet<MAS_PERSON_POSTULANT> _MAS_PERSON_POSTULANT;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTYP_IDChanging(int value);
    partial void OnTYP_IDChanged();
    partial void OnTYP_DESCRIPTIONChanging(string value);
    partial void OnTYP_DESCRIPTIONChanged();
    partial void OnTYP_STATEChanging(System.Nullable<bool> value);
    partial void OnTYP_STATEChanged();
    #endregion
		
		public MAS_TYPE_IDENTIFICATION()
		{
			this._MAS_PERSON_COMPANY = new EntitySet<MAS_PERSON_COMPANY>(new Action<MAS_PERSON_COMPANY>(this.attach_MAS_PERSON_COMPANY), new Action<MAS_PERSON_COMPANY>(this.detach_MAS_PERSON_COMPANY));
			this._MAS_PERSON_POSTULANT = new EntitySet<MAS_PERSON_POSTULANT>(new Action<MAS_PERSON_POSTULANT>(this.attach_MAS_PERSON_POSTULANT), new Action<MAS_PERSON_POSTULANT>(this.detach_MAS_PERSON_POSTULANT));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TYP_ID
		{
			get
			{
				return this._TYP_ID;
			}
			set
			{
				if ((this._TYP_ID != value))
				{
					this.OnTYP_IDChanging(value);
					this.SendPropertyChanging();
					this._TYP_ID = value;
					this.SendPropertyChanged("TYP_ID");
					this.OnTYP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYP_DESCRIPTION", DbType="NVarChar(200)")]
		public string TYP_DESCRIPTION
		{
			get
			{
				return this._TYP_DESCRIPTION;
			}
			set
			{
				if ((this._TYP_DESCRIPTION != value))
				{
					this.OnTYP_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._TYP_DESCRIPTION = value;
					this.SendPropertyChanged("TYP_DESCRIPTION");
					this.OnTYP_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYP_STATE", DbType="Bit")]
		public System.Nullable<bool> TYP_STATE
		{
			get
			{
				return this._TYP_STATE;
			}
			set
			{
				if ((this._TYP_STATE != value))
				{
					this.OnTYP_STATEChanging(value);
					this.SendPropertyChanging();
					this._TYP_STATE = value;
					this.SendPropertyChanged("TYP_STATE");
					this.OnTYP_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_TYPE_IDENTIFICATION_MAS_PERSON_COMPANY", Storage="_MAS_PERSON_COMPANY", ThisKey="TYP_ID", OtherKey="PER_FK_TYPE_IDENTIFICATION")]
		public EntitySet<MAS_PERSON_COMPANY> MAS_PERSON_COMPANY
		{
			get
			{
				return this._MAS_PERSON_COMPANY;
			}
			set
			{
				this._MAS_PERSON_COMPANY.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_TYPE_IDENTIFICATION_MAS_PERSON_POSTULANT", Storage="_MAS_PERSON_POSTULANT", ThisKey="TYP_ID", OtherKey="PER_FK_TYPE_IDENTIFICATION")]
		public EntitySet<MAS_PERSON_POSTULANT> MAS_PERSON_POSTULANT
		{
			get
			{
				return this._MAS_PERSON_POSTULANT;
			}
			set
			{
				this._MAS_PERSON_POSTULANT.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MAS_PERSON_COMPANY(MAS_PERSON_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_TYPE_IDENTIFICATION = this;
		}
		
		private void detach_MAS_PERSON_COMPANY(MAS_PERSON_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_TYPE_IDENTIFICATION = null;
		}
		
		private void attach_MAS_PERSON_POSTULANT(MAS_PERSON_POSTULANT entity)
		{
			this.SendPropertyChanging();
			entity.MAS_TYPE_IDENTIFICATION = this;
		}
		
		private void detach_MAS_PERSON_POSTULANT(MAS_PERSON_POSTULANT entity)
		{
			this.SendPropertyChanging();
			entity.MAS_TYPE_IDENTIFICATION = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_TYPE_INDUSTRY")]
	public partial class MAS_TYPE_INDUSTRY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TYP_ID;
		
		private string _TYP_DESCRIPTION;
		
		private System.Nullable<bool> _TYP_STATE;
		
		private EntitySet<MAS_COMPANY> _MAS_COMPANY;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTYP_IDChanging(int value);
    partial void OnTYP_IDChanged();
    partial void OnTYP_DESCRIPTIONChanging(string value);
    partial void OnTYP_DESCRIPTIONChanged();
    partial void OnTYP_STATEChanging(System.Nullable<bool> value);
    partial void OnTYP_STATEChanged();
    #endregion
		
		public MAS_TYPE_INDUSTRY()
		{
			this._MAS_COMPANY = new EntitySet<MAS_COMPANY>(new Action<MAS_COMPANY>(this.attach_MAS_COMPANY), new Action<MAS_COMPANY>(this.detach_MAS_COMPANY));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYP_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TYP_ID
		{
			get
			{
				return this._TYP_ID;
			}
			set
			{
				if ((this._TYP_ID != value))
				{
					this.OnTYP_IDChanging(value);
					this.SendPropertyChanging();
					this._TYP_ID = value;
					this.SendPropertyChanged("TYP_ID");
					this.OnTYP_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYP_DESCRIPTION", DbType="NVarChar(200)")]
		public string TYP_DESCRIPTION
		{
			get
			{
				return this._TYP_DESCRIPTION;
			}
			set
			{
				if ((this._TYP_DESCRIPTION != value))
				{
					this.OnTYP_DESCRIPTIONChanging(value);
					this.SendPropertyChanging();
					this._TYP_DESCRIPTION = value;
					this.SendPropertyChanged("TYP_DESCRIPTION");
					this.OnTYP_DESCRIPTIONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TYP_STATE", DbType="Bit")]
		public System.Nullable<bool> TYP_STATE
		{
			get
			{
				return this._TYP_STATE;
			}
			set
			{
				if ((this._TYP_STATE != value))
				{
					this.OnTYP_STATEChanging(value);
					this.SendPropertyChanging();
					this._TYP_STATE = value;
					this.SendPropertyChanged("TYP_STATE");
					this.OnTYP_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_TYPE_INDUSTRY_MAS_COMPANY", Storage="_MAS_COMPANY", ThisKey="TYP_ID", OtherKey="COM_FK_TYPE_INDUSTRY")]
		public EntitySet<MAS_COMPANY> MAS_COMPANY
		{
			get
			{
				return this._MAS_COMPANY;
			}
			set
			{
				this._MAS_COMPANY.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MAS_COMPANY(MAS_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_TYPE_INDUSTRY = this;
		}
		
		private void detach_MAS_COMPANY(MAS_COMPANY entity)
		{
			this.SendPropertyChanging();
			entity.MAS_TYPE_INDUSTRY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_USER_COMPANY")]
	public partial class MAS_USER_COMPANY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USE_ID;
		
		private string _USE_EMAIL;
		
		private string _USE_PASSWORD;
		
		private System.Nullable<int> _USE_ATTEMPTS;
		
		private System.Nullable<System.DateTime> _USE_LAST_PASSWORD_CHANGED;
		
		private string _USE_PROFILE_PICTURE;
		
		private System.Nullable<bool> _USE_STATE;
		
		private System.Nullable<int> _USE_FK_PERSON_COMPANY;
		
		private EntityRef<MAS_PERSON_COMPANY> _MAS_PERSON_COMPANY;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSE_IDChanging(int value);
    partial void OnUSE_IDChanged();
    partial void OnUSE_EMAILChanging(string value);
    partial void OnUSE_EMAILChanged();
    partial void OnUSE_PASSWORDChanging(string value);
    partial void OnUSE_PASSWORDChanged();
    partial void OnUSE_ATTEMPTSChanging(System.Nullable<int> value);
    partial void OnUSE_ATTEMPTSChanged();
    partial void OnUSE_LAST_PASSWORD_CHANGEDChanging(System.Nullable<System.DateTime> value);
    partial void OnUSE_LAST_PASSWORD_CHANGEDChanged();
    partial void OnUSE_PROFILE_PICTUREChanging(string value);
    partial void OnUSE_PROFILE_PICTUREChanged();
    partial void OnUSE_STATEChanging(System.Nullable<bool> value);
    partial void OnUSE_STATEChanged();
    partial void OnUSE_FK_PERSON_COMPANYChanging(System.Nullable<int> value);
    partial void OnUSE_FK_PERSON_COMPANYChanged();
    #endregion
		
		public MAS_USER_COMPANY()
		{
			this._MAS_PERSON_COMPANY = default(EntityRef<MAS_PERSON_COMPANY>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int USE_ID
		{
			get
			{
				return this._USE_ID;
			}
			set
			{
				if ((this._USE_ID != value))
				{
					this.OnUSE_IDChanging(value);
					this.SendPropertyChanging();
					this._USE_ID = value;
					this.SendPropertyChanged("USE_ID");
					this.OnUSE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_EMAIL", DbType="NVarChar(100)")]
		public string USE_EMAIL
		{
			get
			{
				return this._USE_EMAIL;
			}
			set
			{
				if ((this._USE_EMAIL != value))
				{
					this.OnUSE_EMAILChanging(value);
					this.SendPropertyChanging();
					this._USE_EMAIL = value;
					this.SendPropertyChanged("USE_EMAIL");
					this.OnUSE_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_PASSWORD", DbType="NVarChar(200)")]
		public string USE_PASSWORD
		{
			get
			{
				return this._USE_PASSWORD;
			}
			set
			{
				if ((this._USE_PASSWORD != value))
				{
					this.OnUSE_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._USE_PASSWORD = value;
					this.SendPropertyChanged("USE_PASSWORD");
					this.OnUSE_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_ATTEMPTS", DbType="Int")]
		public System.Nullable<int> USE_ATTEMPTS
		{
			get
			{
				return this._USE_ATTEMPTS;
			}
			set
			{
				if ((this._USE_ATTEMPTS != value))
				{
					this.OnUSE_ATTEMPTSChanging(value);
					this.SendPropertyChanging();
					this._USE_ATTEMPTS = value;
					this.SendPropertyChanged("USE_ATTEMPTS");
					this.OnUSE_ATTEMPTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_LAST_PASSWORD_CHANGED", DbType="Date")]
		public System.Nullable<System.DateTime> USE_LAST_PASSWORD_CHANGED
		{
			get
			{
				return this._USE_LAST_PASSWORD_CHANGED;
			}
			set
			{
				if ((this._USE_LAST_PASSWORD_CHANGED != value))
				{
					this.OnUSE_LAST_PASSWORD_CHANGEDChanging(value);
					this.SendPropertyChanging();
					this._USE_LAST_PASSWORD_CHANGED = value;
					this.SendPropertyChanged("USE_LAST_PASSWORD_CHANGED");
					this.OnUSE_LAST_PASSWORD_CHANGEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_PROFILE_PICTURE", DbType="NVarChar(200)")]
		public string USE_PROFILE_PICTURE
		{
			get
			{
				return this._USE_PROFILE_PICTURE;
			}
			set
			{
				if ((this._USE_PROFILE_PICTURE != value))
				{
					this.OnUSE_PROFILE_PICTUREChanging(value);
					this.SendPropertyChanging();
					this._USE_PROFILE_PICTURE = value;
					this.SendPropertyChanged("USE_PROFILE_PICTURE");
					this.OnUSE_PROFILE_PICTUREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_STATE", DbType="Bit")]
		public System.Nullable<bool> USE_STATE
		{
			get
			{
				return this._USE_STATE;
			}
			set
			{
				if ((this._USE_STATE != value))
				{
					this.OnUSE_STATEChanging(value);
					this.SendPropertyChanging();
					this._USE_STATE = value;
					this.SendPropertyChanged("USE_STATE");
					this.OnUSE_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_FK_PERSON_COMPANY", DbType="Int")]
		public System.Nullable<int> USE_FK_PERSON_COMPANY
		{
			get
			{
				return this._USE_FK_PERSON_COMPANY;
			}
			set
			{
				if ((this._USE_FK_PERSON_COMPANY != value))
				{
					if (this._MAS_PERSON_COMPANY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSE_FK_PERSON_COMPANYChanging(value);
					this.SendPropertyChanging();
					this._USE_FK_PERSON_COMPANY = value;
					this.SendPropertyChanged("USE_FK_PERSON_COMPANY");
					this.OnUSE_FK_PERSON_COMPANYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_PERSON_COMPANY_MAS_USER_COMPANY", Storage="_MAS_PERSON_COMPANY", ThisKey="USE_FK_PERSON_COMPANY", OtherKey="PER_ID", IsForeignKey=true)]
		public MAS_PERSON_COMPANY MAS_PERSON_COMPANY
		{
			get
			{
				return this._MAS_PERSON_COMPANY.Entity;
			}
			set
			{
				MAS_PERSON_COMPANY previousValue = this._MAS_PERSON_COMPANY.Entity;
				if (((previousValue != value) 
							|| (this._MAS_PERSON_COMPANY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAS_PERSON_COMPANY.Entity = null;
						previousValue.MAS_USER_COMPANY.Remove(this);
					}
					this._MAS_PERSON_COMPANY.Entity = value;
					if ((value != null))
					{
						value.MAS_USER_COMPANY.Add(this);
						this._USE_FK_PERSON_COMPANY = value.PER_ID;
					}
					else
					{
						this._USE_FK_PERSON_COMPANY = default(Nullable<int>);
					}
					this.SendPropertyChanged("MAS_PERSON_COMPANY");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MAS_USER_POSTULANT")]
	public partial class MAS_USER_POSTULANT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _USE_ID;
		
		private string _USE_EMAIL;
		
		private string _USE_PASSWORD;
		
		private System.Nullable<int> _USE_ATTEMPTS;
		
		private System.Nullable<System.DateTime> _USE_PASSWORD_CHANGED;
		
		private string _USE_PROFILE_PICTURE;
		
		private System.Nullable<bool> _USE_STATE;
		
		private System.Nullable<int> _USE_FK_PERSON_POSTULANT;
		
		private EntityRef<MAS_PERSON_POSTULANT> _MAS_PERSON_POSTULANT;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSE_IDChanging(int value);
    partial void OnUSE_IDChanged();
    partial void OnUSE_EMAILChanging(string value);
    partial void OnUSE_EMAILChanged();
    partial void OnUSE_PASSWORDChanging(string value);
    partial void OnUSE_PASSWORDChanged();
    partial void OnUSE_ATTEMPTSChanging(System.Nullable<int> value);
    partial void OnUSE_ATTEMPTSChanged();
    partial void OnUSE_PASSWORD_CHANGEDChanging(System.Nullable<System.DateTime> value);
    partial void OnUSE_PASSWORD_CHANGEDChanged();
    partial void OnUSE_PROFILE_PICTUREChanging(string value);
    partial void OnUSE_PROFILE_PICTUREChanged();
    partial void OnUSE_STATEChanging(System.Nullable<bool> value);
    partial void OnUSE_STATEChanged();
    partial void OnUSE_FK_PERSON_POSTULANTChanging(System.Nullable<int> value);
    partial void OnUSE_FK_PERSON_POSTULANTChanged();
    #endregion
		
		public MAS_USER_POSTULANT()
		{
			this._MAS_PERSON_POSTULANT = default(EntityRef<MAS_PERSON_POSTULANT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int USE_ID
		{
			get
			{
				return this._USE_ID;
			}
			set
			{
				if ((this._USE_ID != value))
				{
					this.OnUSE_IDChanging(value);
					this.SendPropertyChanging();
					this._USE_ID = value;
					this.SendPropertyChanged("USE_ID");
					this.OnUSE_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_EMAIL", DbType="NVarChar(100)")]
		public string USE_EMAIL
		{
			get
			{
				return this._USE_EMAIL;
			}
			set
			{
				if ((this._USE_EMAIL != value))
				{
					this.OnUSE_EMAILChanging(value);
					this.SendPropertyChanging();
					this._USE_EMAIL = value;
					this.SendPropertyChanged("USE_EMAIL");
					this.OnUSE_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_PASSWORD", DbType="NVarChar(200)")]
		public string USE_PASSWORD
		{
			get
			{
				return this._USE_PASSWORD;
			}
			set
			{
				if ((this._USE_PASSWORD != value))
				{
					this.OnUSE_PASSWORDChanging(value);
					this.SendPropertyChanging();
					this._USE_PASSWORD = value;
					this.SendPropertyChanged("USE_PASSWORD");
					this.OnUSE_PASSWORDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_ATTEMPTS", DbType="Int")]
		public System.Nullable<int> USE_ATTEMPTS
		{
			get
			{
				return this._USE_ATTEMPTS;
			}
			set
			{
				if ((this._USE_ATTEMPTS != value))
				{
					this.OnUSE_ATTEMPTSChanging(value);
					this.SendPropertyChanging();
					this._USE_ATTEMPTS = value;
					this.SendPropertyChanged("USE_ATTEMPTS");
					this.OnUSE_ATTEMPTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_PASSWORD_CHANGED", DbType="Date")]
		public System.Nullable<System.DateTime> USE_PASSWORD_CHANGED
		{
			get
			{
				return this._USE_PASSWORD_CHANGED;
			}
			set
			{
				if ((this._USE_PASSWORD_CHANGED != value))
				{
					this.OnUSE_PASSWORD_CHANGEDChanging(value);
					this.SendPropertyChanging();
					this._USE_PASSWORD_CHANGED = value;
					this.SendPropertyChanged("USE_PASSWORD_CHANGED");
					this.OnUSE_PASSWORD_CHANGEDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_PROFILE_PICTURE", DbType="NVarChar(200)")]
		public string USE_PROFILE_PICTURE
		{
			get
			{
				return this._USE_PROFILE_PICTURE;
			}
			set
			{
				if ((this._USE_PROFILE_PICTURE != value))
				{
					this.OnUSE_PROFILE_PICTUREChanging(value);
					this.SendPropertyChanging();
					this._USE_PROFILE_PICTURE = value;
					this.SendPropertyChanged("USE_PROFILE_PICTURE");
					this.OnUSE_PROFILE_PICTUREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_STATE", DbType="Bit")]
		public System.Nullable<bool> USE_STATE
		{
			get
			{
				return this._USE_STATE;
			}
			set
			{
				if ((this._USE_STATE != value))
				{
					this.OnUSE_STATEChanging(value);
					this.SendPropertyChanging();
					this._USE_STATE = value;
					this.SendPropertyChanged("USE_STATE");
					this.OnUSE_STATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USE_FK_PERSON_POSTULANT", DbType="Int")]
		public System.Nullable<int> USE_FK_PERSON_POSTULANT
		{
			get
			{
				return this._USE_FK_PERSON_POSTULANT;
			}
			set
			{
				if ((this._USE_FK_PERSON_POSTULANT != value))
				{
					if (this._MAS_PERSON_POSTULANT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUSE_FK_PERSON_POSTULANTChanging(value);
					this.SendPropertyChanging();
					this._USE_FK_PERSON_POSTULANT = value;
					this.SendPropertyChanged("USE_FK_PERSON_POSTULANT");
					this.OnUSE_FK_PERSON_POSTULANTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MAS_PERSON_POSTULANT_MAS_USER_POSTULANT", Storage="_MAS_PERSON_POSTULANT", ThisKey="USE_FK_PERSON_POSTULANT", OtherKey="PER_ID", IsForeignKey=true)]
		public MAS_PERSON_POSTULANT MAS_PERSON_POSTULANT
		{
			get
			{
				return this._MAS_PERSON_POSTULANT.Entity;
			}
			set
			{
				MAS_PERSON_POSTULANT previousValue = this._MAS_PERSON_POSTULANT.Entity;
				if (((previousValue != value) 
							|| (this._MAS_PERSON_POSTULANT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MAS_PERSON_POSTULANT.Entity = null;
						previousValue.MAS_USER_POSTULANT.Remove(this);
					}
					this._MAS_PERSON_POSTULANT.Entity = value;
					if ((value != null))
					{
						value.MAS_USER_POSTULANT.Add(this);
						this._USE_FK_PERSON_POSTULANT = value.PER_ID;
					}
					else
					{
						this._USE_FK_PERSON_POSTULANT = default(Nullable<int>);
					}
					this.SendPropertyChanged("MAS_PERSON_POSTULANT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
